#!/usr/bin/env bash

# check if called
if [[ $# -eq 1 ]]; then
  selected=$1
else
  # prompt fzf session dir selection
  selected=$(find ~/Repos/github.com/ ~/personal ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

# get basename and check if tmux running
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# if tmux not running, script not inside tmux session
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  # create new session with name and start in selected dir
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

# if tmux session does not exist
if ! tmux has-session -t=$selected_name 2> /dev/null; then
  # create new detached session with selected name and start in selected dir
  tmux new-session -ds $selected_name -c $selected
fi

# attach to session
tmux switch-client -t $selected_name

